### element acessing row/column

In [1]:
#loc-->location based
#iloc-->index location based

In [4]:
import pandas as pd
df=pd.DataFrame({"name":['puppy',"pinky",'pop','push'],"rollnumber":[501,502,503,504],"branch":["cse","ece",'civil','eee']})
df

name  rollnumber branch
0  puppy         501    cse
1  pinky         502    ece
2    pop         503  civil
3   push         504    eee

In [7]:
df=pd.DataFrame({"name":['puppy',"pinky",'pop','push'],"rollnumber":[501,502,503,504],"branch":["cse","ece",'civil','eee']},index=[1,2,3,4])
df

name  rollnumber branch
1  puppy         501    cse
2  pinky         502    ece
3    pop         503  civil
4   push         504    eee

In [12]:
df.loc[1]

name          puppy
rollnumber      501
branch          cse
Name: 1, dtype: object

In [18]:
df.loc[2]['rollnumber']

502

In [19]:
df.iloc[3]#in iloc index start from 0 its self will changing the index also

name          push
rollnumber     504
branch         eee
Name: 4, dtype: object

In [22]:
df.iloc[0]['name']

'puppy'

In [23]:
df.iloc[0:3]["name"]

1    puppy
2    pinky
3      pop
Name: name, dtype: object

In [25]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 4 entries, 1 to 4
Data columns (total 3 columns):
name          4 non-null object
rollnumber    4 non-null int64
branch        4 non-null object
dtypes: int64(1), object(2)
memory usage: 288.0+ bytes


In [27]:
df.describe()

rollnumber
count    4.000000
mean   502.500000
std      1.290994
min    501.000000
25%    501.750000
50%    502.500000
75%    503.250000
max    504.000000

In [28]:
df.count()

name          4
rollnumber    4
branch        4
dtype: int64

In [30]:
df.dtypes

name          object
rollnumber     int64
branch        object
dtype: object

In [31]:
df.count(axis=1)

1    3
2    3
3    3
4    3
dtype: int64

In [32]:
df.count(axis=0)

name          4
rollnumber    4
branch        4
dtype: int64

In [36]:
df.set_index(["rollnumber"])

name branch
rollnumber              
501         puppy    cse
502         pinky    ece
503           pop  civil
504          push    eee

In [37]:
df.set_index(["name","branch"])

rollnumber
name  branch            
puppy cse            501
pinky ece            502
pop   civil          503
push  eee            504

In [39]:
frame=pd.Series([1,2,3,4,5,''])
frame

0    1
1    2
2    3
3    4
4    5
5     
dtype: object

In [41]:
frame.isnull()

0    False
1    False
2    False
3    False
4    False
5    False
dtype: bool

In [42]:
frame.describe()

count     6
unique    6
top       5
freq      1
dtype: int64

In [43]:
frame.count()

6

### creating dataframe using numpy

In [6]:
import numpy as np
a=np.arange(1,11)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [47]:
a.reshape(2,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [49]:
data=pd.DataFrame(np.arange(12))
data

0
0    0
1    1
2    2
3    3
4    4
5    5
6    6
7    7
8    8
9    9
10  10
11  11

In [51]:
data=pd.DataFrame(np.arange(12).reshape(3,4))
data

0  1   2   3
0  0  1   2   3
1  4  5   6   7
2  8  9  10  11

In [55]:
data=pd.DataFrame(np.arange(12).reshape(3,4),columns=['a','b','c','d'])
data

a  b   c   d
0  0  1   2   3
1  4  5   6   7
2  8  9  10  11

In [69]:
data=pd.DataFrame(np.arange(12).reshape(3,4),columns=['a','b','c','d'],index=['w','y','z'])
data

a  b   c   d
w  0  1   2   3
y  4  5   6   7
z  8  9  10  11

In [63]:
d2=pd.DataFrame(np.arange(20).reshape(4,5),columns=list('abcde'),index=list('wxyz'))
d2

a   b   c   d   e
w   0   1   2   3   4
x   5   6   7   8   9
y  10  11  12  13  14
z  15  16  17  18  19

In [81]:
d2.loc['x','c']=np.nan
d2

a   b     c   d   e
w   0   1   2.0   3   4
x   5   6   NaN   8   9
y  10  11  12.0  13  14
z  15  16  17.0  18  19

In [66]:
d2.isnull()

a      b      c      d      e
w  False  False  False  False  False
x  False  False   True  False  False
y  False  False  False  False  False
z  False  False  False  False  False

In [67]:
d2.isnull().sum()

a    0
b    0
c    1
d    0
e    0
dtype: int64

In [70]:
ad1=d2+data

a     b     c     d   e
w   0.0   2.0   4.0   6.0 NaN
x   NaN   NaN   NaN   NaN NaN
y  14.0  16.0  18.0  20.0 NaN
z  23.0  25.0  27.0  29.0 NaN

In [75]:
ad2=d2.add(data)
ad2

a     b     c     d   e
w   0.0   2.0   4.0   6.0 NaN
x   NaN   NaN   NaN   NaN NaN
y  14.0  16.0  18.0  20.0 NaN
z  23.0  25.0  27.0  29.0 NaN

In [82]:
d2.add(data,fill_value=3)


a     b     c     d     e
w   0.0   2.0   4.0   6.0   7.0
x   8.0   9.0   NaN  11.0  12.0
y  14.0  16.0  18.0  20.0  17.0
z  23.0  25.0  27.0  29.0  22.0

In [78]:
d2

a   b     c   d   e
w   0   1   2.0   3   4
x   5   6   NaN   8   9
y  10  11  12.0  13  14
z  15  16  17.0  18  19

### generating random values

In [85]:
np.random.randn(2,5)

array([[ 1.00877672, -0.8269748 , -1.48269658,  0.67150325, -1.38542098],
       [-2.10005092,  0.35198885, -0.2592637 ,  0.39886016, -1.95915584]])

In [86]:
np.random.rand(2,5)

array([[0.55828051, 0.5819896 , 0.04432956, 0.75125883, 0.9914511 ],
       [0.59106041, 0.91748542, 0.91685137, 0.84397362, 0.09798465]])

#### creating dataframe with random values

In [89]:
t=pd.DataFrame(np.random.randn(3,4))
t

0         1         2         3
0  0.074880  0.455455 -0.910571  0.631222
1 -1.064597 -1.695166  1.042879  0.664242
2 -0.707924 -0.077222 -0.180869  0.071994

In [102]:
t=pd.DataFrame(np.random.randn(3,4),columns=(['s1','s2','s3','s4']),index=list('xyz'))
t

s1        s2        s3        s4
x -0.624003 -1.751556  0.228386  0.926347
y -1.313643 -0.028883  2.283897 -0.257387
z  0.214005  1.434761 -1.468094  0.506689

#### data replacing

In [107]:
r3=pd.DataFrame({11:[4,5,6],12:[3,45,6],13:[12,34,56]})
r3

11  12  13
0   4   3  12
1   5  45  34
2   6   6  56

In [113]:
r31=r3.replace(4,20)
r31

11  12  13
0  20   3  12
1   5  45  34
2   6   6  56

In [112]:
r32=r3.replace([12,45,6],[111,222,333])
r32

11   12   13
0    4    3  111
1    5  222   34
2  333  333   56

#### index sorting and ranking

In [128]:
r3.reindex=['a','b','c']
r3

s2  s3  s1
0   4   3  12
1   5  45  34
2   6   6  56

In [121]:
r33.sort_index()

11  12  13
a NaN NaN NaN
b NaN NaN NaN
c NaN NaN NaN

In [125]:
r3.columns=['s2','s3','s1']
r3

s2  s3  s1
0   4   3  12
1   5  45  34
2   6   6  56

In [126]:
r3.sort_index(axis=1)

s1  s2  s3
0  12   4   3
1  34   5  45
2  56   6   6

In [4]:
#groupby
import pandas as pd
animal_df=pd.DataFrame({"name":['dog','cat','tiger','dog','cat'],'place':['home','zoo','forest','home','zoo'],'features':['barking','shouting','hunting','shouting','barking']})
animal_df

name   place  features
0    dog    home   barking
1    cat     zoo  shouting
2  tiger  forest   hunting
3    dog    home  shouting
4    cat     zoo   barking

In [135]:
animal_df.groupby('name').sum()

place         features
name                            
cat      zoozoo  shoutingbarking
dog    homehome  barkingshouting
tiger    forest          hunting

In [136]:
animal_df.groupby('name').count()

place  features
name                  
cat        2         2
dog        2         2
tiger      1         1

In [137]:
animal_df.groupby(['name','features']).sum()

place
name  features        
cat   barking      zoo
      shouting     zoo
dog   barking     home
      shouting    home
tiger hunting   forest

In [138]:
animal_df.groupby(['name','features']).count()

place
name  features       
cat   barking       1
      shouting      1
dog   barking       1
      shouting      1
tiger hunting       1

#### ranking

In [7]:
animal_df1=pd.DataFrame({"name":['dog','hen','tiger','dog','hen'],'place':['home','zoo','forest','home','zoo'],'no.of legs':[4,2,4,2,np.nan]})
animal_df1

name   place  no.of legs
0    dog    home         4.0
1    hen     zoo         2.0
2  tiger  forest         4.0
3    dog    home         2.0
4    hen     zoo         NaN

In [141]:
animal_df1['rank1']=animal_df1['no.of legs'].rank()
animal_df1

name   place  no.of legs  rank1
0    dog    home         4.0    3.5
1    hen     zoo         2.0    1.5
2  tiger  forest         4.0    3.5
3    dog    home         2.0    1.5
4    hen     zoo         NaN    NaN

In [142]:
animal_df1['max-rank1']=animal_df1['no.of legs'].rank(method='max')
animal_df1

name   place  no.of legs  rank1  max-rank1
0    dog    home         4.0    3.5        4.0
1    hen     zoo         2.0    1.5        2.0
2  tiger  forest         4.0    3.5        4.0
3    dog    home         2.0    1.5        2.0
4    hen     zoo         NaN    NaN        NaN

In [10]:
animal_df1['max-rank1']=animal_df1['no.of legs'].rank(method='first')
animal_df1

name   place  no.of legs  max-rank1
0    dog    home         4.0        3.0
1    hen     zoo         2.0        1.0
2  tiger  forest         4.0        4.0
3    dog    home         2.0        2.0
4    hen     zoo         NaN        NaN

In [8]:
animal_df1['max-rank1']=animal_df1['no.of legs'].rank(na_option='bottom')
animal_df1

name   place  no.of legs  max-rank1
0    dog    home         4.0        3.5
1    hen     zoo         2.0        1.5
2  tiger  forest         4.0        3.5
3    dog    home         2.0        1.5
4    hen     zoo         NaN        5.0

In [9]:
animal_df1['max-rank1']=animal_df1['no.of legs'].rank(pct=True)
animal_df1

name   place  no.of legs  max-rank1
0    dog    home         4.0      0.875
1    hen     zoo         2.0      0.375
2  tiger  forest         4.0      0.875
3    dog    home         2.0      0.375
4    hen     zoo         NaN        NaN

#### categories

In [11]:
d_f=pd.DataFrame({'x':[1,2,3,4,5],'y':[6,7,8,9,10]})
d_f

x   y
0  1   6
1  2   7
2  3   8
3  4   9
4  5  10

In [12]:
d_f['dd']=d_f['y'].astype('category')

In [13]:
d_f

x   y  dd
0  1   6   6
1  2   7   7
2  3   8   8
3  4   9   9
4  5  10  10

In [15]:
d_f['dd'].cat.categories=['good_f['dd'].cat.categories=['good','bad','average','not bad','worst']

In [16]:
d_f

x   y       dd
0  1   6     good
1  2   7      bad
2  3   8  average
3  4   9  not bad
4  5  10    worst

In [18]:
d_f['dd']=d_f['dd'].set_categories=['good','bad','average','not bad','worst']
d_f

x   y       dd
0  1   6     good
1  2   7      bad
2  3   8  average
3  4   9  not bad
4  5  10    worst

In [19]:
d_f.sort_values('dd')

x   y       dd
2  3   8  average
1  2   7      bad
0  1   6     good
3  4   9  not bad
4  5  10    worst

#### reading data


In [20]:
df1=pd.read_table('sample.txt')
df1

C:\Users\public\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: read_table is deprecated, use read_csv instead, passing sep='\t'.
  """Entry point for launching an IPython kernel.


a b c
0  1 2 3
1  4 5 6
2  7 8 9

In [21]:
df1=pd.read_table('ex1.csv')

C:\Users\public\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: read_table is deprecated, use read_csv instead, passing sep='\t'.
  """Entry point for launching an IPython kernel.


In [22]:
df1


a,b,c,d,message
0   1,2,3,4,hello
1   5,6,7,8,world
2  9,10,11,12,foo

In [23]:
df1=pd.read_table('ex1.csv',sep=',')
df1

C:\Users\public\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: read_table is deprecated, use read_csv instead.
  """Entry point for launching an IPython kernel.


a   b   c   d message
0  1   2   3   4   hello
1  5   6   7   8   world
2  9  10  11  12     foo